### ISSUE TITLE
Fails to connect etherpad

### ISSUE THREAD

**Issue by atondwal** [guyzmo/vim-etherpad#1]
After I source `plugin/vim-etherpad.vim`, and run `:Etherpad` I get this:

```
Exception AttributeError: "'SocketIO' object has no attribute '_socketIO'" in <bound method SocketIO.__del__ of <s
ocketIO_client.SocketIO object at 0x7f35ea6442d0>> ignored
ERROR:vim_etherpad:__init__() got an unexpected keyword argument 'disc_cb'
Traceback (most recent call last):
  File "<string>", line 242, in _launch_epad
  File "build/bdist.linux-x86_64/egg/py_etherpad/SocketIOClient.py", line 41, in __init__
    self.__init()
  File "build/bdist.linux-x86_64/egg/py_etherpad/SocketIOClient.py", line 50, in __init
    cb=self.cb, **self.kwarg)
TypeError: __init__() got an unexpected keyword argument 'disc_cb'
Couldn't connect to Etherpad: http://localhost:9001/p/test
```

The tests for `py_etherpad` seem to work though, so that's probably not the problem:
![2013-07-17-232444_1920x1080_scrot](https://f.cloud.github.com/assets/343048/816841/0d9c3f52-ef5a-11e2-8e9e-bd1d0793d8fe.png)

**Comment by pickfire** [comment]
It didn't works for me either. When I run `vim`, [this errors](http://pastebin.com/8gDKCWsu) show up.
And when I run `:Etherpad https://pad.riseup.net/p/test`, [some errors](http://pastebin.com/pau6S7tx) shows up and I can't use it.

**Comment by pickfire** [comment]
It works now after I install the `PyEtherpadLite`, but now there is another [error](http://pastebin.com/S8K6dUjp).
